
modLoader="javafml" 
loaderVersion="[27,)" 
issueTrackerURL="http://github.com/kamefrede/simplymoretea/issues" 
[[mods]] #mandatory
modId="simplymoretea"
version="0.0.1" 
displayName="Simply More Tea" 
updateJSONURL="http://github.com/kamefrede/simplymoretea" 
displayURL="http://github.com/kamefrede/simplymoretea"
logoFile="simplymoretea.png"
credits="yrsegal, KnightMiner"
authors="Kamefrede" 
description='''
Simply more Tea!
(and Infusions)
'''


[[dependencies.simplymoretea]]
    modId="forge"
    mandatory=true
    versionRange="[27,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.simplymoretea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplymoretea]]
    modId="simplytea"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="NONE"
    side="BOTH"